### ISSUE TITLE
Cannot be used in the REPL

### ISSUE THREAD

**Issue by webJose** [orefalo/svelte-virtuallists#25] opened 2024-11-21 15:46 UTC
When trying the below example in the REPL, this error shows up:

> https://unpkg.com/browse/svelte-virtuallists@1.4.0/dist/ (1:0): Expression expected (Note that you need plugins to import files that are not JavaScript)

```svelte
<script>
	import { VirtualList } from 'svelte-virtuallists';

	const data = ['A', 'B', 'C', 'D', 'E', 'F' /* ... */];
</script>

<VirtualList class='mystyle' style='width:100%;height=600px' items={data}>
	{#snippet vl_slot({ index, item })}
		<div>
			Row: #{index} Item: {item}
		</div>
	{/snippet}
</VirtualList>
```

**Comment by orefalo** [comment] 2024-11-21 19:20
They modified Svelte 5 so packages now bundle TypeScript code instead of compiled JavaScript.
As a result, REPL will load the dependency and show an error because TypeScript is not installed.
A similar issue occurs when using PostCSS or related tools.

It's one of the reasons I remove the REPL example for the landing page...

If you know of an alternative, please share..

**Comment by orefalo** [comment] 2024-12-29 07:15
closing - not a bug, a REPL limitation at this point

**Closed by orefalo** 2024-12-29 07:15 UTC
